### ISSUE TITLE
Get task by id

### ISSUE THREAD

**Issue by krau** [GopeedLab/gopeed-js#2]
Gopeed 在 [api.go](https://github.com/GopeedLab/gopeed/blob/78b5b8a78bdf3314e6123a96139994b2d26eef24/pkg/rest/api.go#L118) 中提供了通过 id 获取单个任务的 api, 但是我没有在 @gopeed/rest 中找到这个方法, 希望补充进去.

**Comment by monkeyWie** [comment]
1.3.8版本已经加上了哦
